version: "3"

services:
  app:
    container_name: nomess-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports: 
    - "8080:8080"
    environment:
      - NOMESS_PORT=8080
      - NOMESS_DB_ORM_DRIVER=postgres
      - NOMESS_DB_ORM_DSN=host='nomess-postgres-db' user=nomess-user password=nomess-passw dbname=nomess-db port=5432 sslmode=disable TimeZone=America/New_York
  db:
    container_name: nomess-postgres-db
    image: postgres:alpine3.18
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=nomess-db
      - POSTGRES_USER=nomess-user
      - POSTGRES_PASSWORD=nomess-passw
      - POSTGRES_HOST_AUTH_METHOD=password
